// react19-weather-frontend/react-weather-frontend/src/App.tsx
import React, { useState } from 'react';
import './styles/global.css';
import SearchForm from './components/SearchForm';
import WeatherCard from './components/WeatherCard';
import Spinner from './components/Spinner';
import { getWeather, getCityName } from './services/weatherService';
import type { WeatherResponse } from './types/weather';

export default function App() {
  const [city, setCity] = useState('');
  const [latitude, setLatitude] = useState('');
  const [longitude, setLongitude] = useState('');
  const [weather, setWeather] = useState<WeatherResponse | null>(null);
  const [events, setEvents] = useState<string[]>([]);
  const [errorMsg, setErrorMsg] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  function resetCoordinates() {
    setLatitude('');
    setLongitude('');
  }

  function validateCityName(name: string) {
    if (!name?.trim()) {
      setErrorMsg('Please enter a valid city name.');
      return false;
    }
    if (!/^[a-zA-Z\s\-]+$/.test(name.trim())) {
      setErrorMsg('City name can only contain letters, spaces, and hyphens.');
      return false;
    }
    return true;
  }

  async function fetchByCity() {
    resetCoordinates();
    setErrorMsg('');
    if (!validateCityName(city)) return;

    setIsLoading(true);
    try {
      const data = await getWeather({ city });
      setWeather(data);
      setEvents(data.events || []);
    } catch (err: any) {
      console.error(err);
      setWeather(null);
      setErrorMsg(err?.message || 'Error fetching weather data by city.');
    } finally {
      setIsLoading(false);
    }
  }

  async function fetchByLatLon() {
    setCity('');
    setErrorMsg('');
    if (!latitude || !longitude) {
      setErrorMsg('Please enter both latitude and longitude.');
      return;
    }

    const latNum = Number(latitude);
    const lonNum = Number(longitude);
    if (!Number.isFinite(latNum) || !Number.isFinite(lonNum)) {
      setErrorMsg('Latitude and longitude must be valid numbers.');
      return;
    }

    setIsLoading(true);
    try {
      const data = await getWeather({ lat: latNum, lon: lonNum });
      setWeather(data);
      setEvents(data.events || []);
      try {
        const cityRes = await getCityName(latNum, lonNum);
        if (Array.isArray(cityRes) && cityRes.length > 0) {
          setCity(cityRes[0].name || '');
        } else if ((cityRes as any)?.name) {
          setCity((cityRes as any).name);
        }
      } catch (e) {
        console.warn('city lookup failed', e);
      }
    } catch (err: any) {
      console.error(err);
      setWeather(null);
      setErrorMsg(err?.message || 'Error fetching weather data by coordinates.');
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <main className="main">
      <div className="content">
        <h1 className="subtitle">Search Today's Live Weather Forecast🌦️</h1>

        <SearchForm
          city={city}
          setCity={setCity}
          latitude={latitude}
          setLatitude={setLatitude}
          longitude={longitude}
          setLongitude={setLongitude}
          onSearchByCity={fetchByCity}
          onSearchByLatLon={fetchByLatLon}
          isLoading={isLoading}
        />

        {errorMsg && <div className="error-msg">{errorMsg}</div>}
        {isLoading && <Spinner />}

        {weather && !isLoading && <WeatherCard weather={weather} />}
      </div>
    </main>
  );
}

// angular19-weather-frontend/angular-weather-frontend/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { WeatherService } from './weather.service';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  imports: [RouterOutlet, CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-weather-frontend';

  latitude: number | null = null;
  longitude: number | null = null;
  city: string = '';

  weather: any;
  errorMsg: string = '';

  constructor(private weatherService: WeatherService) {}

  fetchWeatherByCity() {
    if (!this.city || this.city.trim().length === 0) {
      this.weather = null;
      this.errorMsg = 'Please enter a valid city name.';
      return;
    }

    // Only allow letters, spaces, and hyphens
    if (!/^[a-zA-Z\s\-]+$/.test(this.city.trim())) {
      this.weather = null;
      this.errorMsg = 'City name can only contain letters, spaces, and hyphens.';
      return;
    }

    this.errorMsg = '';
    this.weatherService.getWeather(this.city).subscribe({
      next: (data) => (this.weather = data),
      error: (err) => {
        this.weather = null;
        this.errorMsg = 'Error fetching weather data for city.';
        console.error('Error fetching weather by city', err);
      }
    });
  }

  fetchWeatherByLatLon() {
    if (this.latitude == null || this.longitude == null) {
      this.weather = null;
      this.errorMsg = 'Please enter both latitude and longitude.';
      return;
    }

    this.errorMsg = '';
    this.weatherService.getWeather(undefined, this.latitude, this.longitude).subscribe({
      next: (data) => (this.weather = data),
      error: (err) => {
        this.weather = null;
        this.errorMsg = 'Error fetching weather data by coordinates.';
        console.error('Error fetching weather by lat/lon', err);
      }
    });
  }
}

<main class="main">
  <div class="content">
    <h1>Angular 19 Weather App</h1>
    <h2 class="subtitle">
      Fetch Live Weather Data
    </h2>

    <div class="weather-form-row">
      <!-- City Search -->
      <div class="weather-form-section">
        <form #cityForm="ngForm" (ngSubmit)="fetchWeatherByCity()" autocomplete="off">
          <div class="input-row">
            <input
              type="text"
              name="city"
              [(ngModel)]="city"
              placeholder="City Name"
              class="weather-input"
              required
              pattern="^[a-zA-Z\s\-]+$"
              #cityInput="ngModel"
              (keydown.enter)="fetchWeatherByCity()"
            />
          </div>
          <div *ngIf="cityInput.invalid && (cityInput.dirty || cityInput.touched)" class="error-msg">
            <span *ngIf="cityInput.errors?.['required']">City name is required.</span>
          </div>
          <div *ngIf="cityInput.invalid && cityInput.errors?.['pattern'] && (cityInput.dirty || cityInput.touched)" class="error-msg">
            Only letters, spaces, and hyphens are allowed.
          </div>
          <button [disabled]="cityInput.invalid" class="weather-btn">
            Fetch by City
          </button>
        </form>
      </div>

      <div class="weather-divider"></div>

      <!-- Lat / Lon Search -->
      <div class="weather-form-section">
        <div class="input-row">
          <input
            type="number"
            [(ngModel)]="latitude"
            placeholder="Latitude"
            step="any"
            class="weather-input"
            (keydown.enter)="fetchWeatherByLatLon()"
          />
          <input
            type="number"
            [(ngModel)]="longitude"
            placeholder="Longitude"
            step="any"
            class="weather-input"
            (keydown.enter)="fetchWeatherByLatLon()"
          />
        </div>
        <button (click)="fetchWeatherByLatLon()" class="weather-btn">
          Fetch by Latitude/Longitude
        </button>
      </div>
    </div>

    <div *ngIf="errorMsg" class="error-msg">{{ errorMsg }}</div>

    <div *ngIf="weather" class="weather-result">
      <h3>
        Current Weather of
        <span *ngIf="weather.city">{{ weather.city }}</span>
        <span *ngIf="!weather.city">
          ({{ weather.latitude }}, {{ weather.longitude }})
        </span>
      </h3>
      <p><strong>🌍 Latitude:</strong> {{ weather.latitude }}</p>
      <p><strong>🌏 Longitude:</strong> {{ weather.longitude }}</p>
      <p><strong>🌡️ Temperature:</strong> {{ weather.current_weather?.temperature }} °C</p>
      <p><strong>💨 Windspeed:</strong> {{ weather.current_weather?.windspeed }} km/h</p>
      <p><strong>🧭 Wind Direction:</strong> {{ weather.current_weather?.winddirection }}°</p>
      <p><strong>⏰ Time:</strong> {{ weather.current_weather?.time | date:'medium' }}</p>
      <p><strong>🌦️ Weather Code:</strong> {{ weather.current_weather?.weathercode }}</p>
    </div>
  </div>
</main>
<router-outlet />
